apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eb2vl95qa-nodejs 
  janus-idp.io/tekton: eb2vl95qa-nodejs
  backstage.io/kubernetes-id: eb2vl95qa-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eb2vl95qa-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  