apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eb2vl95qa-nodejs
  janus-idp.io/tekton: eb2vl95qa-nodejs
  backstage.io/kubernetes-id: eb2vl95qa-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eb2vl95qa-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
